import { Env } from "./types";
import * as jose from "jose";
import { v5 as uuidv5 } from "uuid";

export interface OpenIdConfiguration {
  issuer: string;
  authorization_endpoint: string;
  jwks_uri: string;
  token_endpoint: string;
  userinfo_endpoint: string;
  end_session_endpoint: string;
  scopes_supported: string[];
  response_types_supported: string[];
  token_endpoint_auth_methods_supported: string[];
}

interface UserData {
  firstName: string;
  lastName: string;
  email: string;
}

export async function generatePEM(): Promise<string> {
  // Use jose library to generate a key that can be exported as JWK
  const { privateKey } = await jose.generateKeyPair("RS256", {
    extractable: true,
  });

  // Export as PKCS8 PEM
  const pem = await jose.exportPKCS8(privateKey);
  return pem;
}

export async function ensurePEM(env: Env): Promise<string> {
  await env.DB.prepare(
    `
    CREATE TABLE IF NOT EXISTS local_oidc_secrets (
      id INTEGER PRIMARY KEY,
      pem TEXT NOT NULL,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      autogenerated BOOLEAN DEFAULT FALSE
    )
  `
  ).run();

  // Check if a PEM already exists in the database
  const existing = await env.DB.prepare(
    `
    SELECT pem FROM local_oidc_secrets WHERE id = 1
  `
  ).first<{ pem: string }>();

  if (existing) {
    return existing.pem;
  }

  // Generate a new PEM if none exists
  const privateKey = await generatePEM();

  const result = await env.DB.prepare(
    `
    INSERT INTO local_oidc_secrets (id, pem, autogenerated, created_at)
    VALUES (1, ?, TRUE, CURRENT_TIMESTAMP)
    ON CONFLICT(id) DO NOTHING
    RETURNING pem
  `
  )
    .bind(privateKey)
    .first<{ pem: string }>();

  if (!result) {
    // If there was a conflict, then nothing is returned, so we need to query again
    const existing = await env.DB.prepare(
      `
      SELECT pem FROM local_oidc_secrets WHERE id = 1
    `
    ).first<{ pem: string }>();
    return existing!.pem;
  }

  return result.pem;
}

function getBaseUrl(request: Request): string {
  const url = new URL(request.url);
  return `${url.protocol}//${url.host}`;
}

function generateOpenIdConfiguration(
  baseUrl: string,
  env: Env
): OpenIdConfiguration {
  return {
    issuer: `${baseUrl}/local_oidc`,
    authorization_endpoint:
      env.LOCAL_OIDC_AUTHORIZATION_ENDPOINT ??
      "http://localhost:5173/local_oidc/authorize",
    jwks_uri: `${baseUrl}/local_oidc/.well-known/jwks.json`,
    token_endpoint: `${baseUrl}/local_oidc/token`,
    userinfo_endpoint: `${baseUrl}/local_oidc/userinfo`,
    end_session_endpoint: `${baseUrl}/local_oidc/logout`,
    scopes_supported: ["profile", "email", "openid"],
    response_types_supported: ["code"],
    token_endpoint_auth_methods_supported: ["client_secret_post"],
  };
}

async function handleOpenIdConfiguration(
  request: Request,
  env: Env
): Promise<Response> {
  const baseUrl = getBaseUrl(request);
  const config = generateOpenIdConfiguration(baseUrl, env);

  return new Response(JSON.stringify(config, null, 2), {
    status: 200,
    headers: {
      "Content-Type": "application/json",
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Methods": "GET, OPTIONS",
      "Access-Control-Allow-Headers": "Content-Type",
    },
  });
}

function getUserId(userData: UserData): string {
  // We want the userId to always be the same for a given email
  const nullNamespace = "00000000-0000-0000-0000-000000000000";
  return uuidv5(userData.email.toLowerCase(), nullNamespace);
}

async function generateTokens(
  userData: UserData,
  env: Env,
): Promise<{
  access_token: string;
  token_type: string;
  refresh_token: string;
  id_token: string;
  expires_in: number;
  scope: string;
}> {
    const pem = await ensurePEM(env);
    const privateKey = await jose.importPKCS8(pem, "RS256", {
      extractable: true,
    });
  const userId = getUserId(userData);
  const now = Math.floor(Date.now() / 1000);

  const basePayload = {
    sub: userId,
    given_name: userData.firstName,
    family_name: userData.lastName,
    email: userData.email,
    iss: env.AUTH_ISSUER,
    aud: "local-anode-client",
    iat: now,
  };

  const accessTokenPayload = {
    ...basePayload,
    exp: now + 5 * 60, // 5 minutes
  };

  // Use a new timestamp for refresh token to ensure it's different
  const refreshNow = Math.floor(Date.now() / 1000);
  const refreshTokenPayload = {
    ...basePayload,
    iat: refreshNow,
    exp: refreshNow + 365 * 24 * 60 * 60, // 1 year
  };

  const accessToken = await new jose.SignJWT(accessTokenPayload)
    .setProtectedHeader({ alg: "RS256", kid: "1" })
    .sign(privateKey);

  const refreshToken = await new jose.SignJWT(refreshTokenPayload)
    .setProtectedHeader({ alg: "RS256", kid: "1" })
    .sign(privateKey);

  return {
    access_token: accessToken,
    token_type: "Bearer",
    expires_in: 300,
    refresh_token: refreshToken,
    id_token: accessToken,
    scope: "openid profile email",
  };
}

async function handleToken(request: Request, env: Env): Promise<Response> {
  // Parse form data instead of URL search params
  const formData = await request.formData();
  const clientId = formData.get("client_id") as string;
  const redirectUri = formData.get("redirect_uri") as string;
  const code = formData.get("code") as string;
  const grantType = formData.get("grant_type") as string;
  const refreshToken = formData.get("refresh_token") as string;

  console.log("formData", formData);

  if (clientId !== "local-anode-client") {
    console.log("Invalid client_id", clientId);
    return new Response("Invalid client_id", { status: 400 });
  }

  if (grantType === "authorization_code") {
    if (!redirectUri || !redirectUri.startsWith("http://localhost")) {
      console.log("Invalid redirect_uri", redirectUri);
      return new Response("Invalid redirect_uri", { status: 400 });
    }

    if (!code) {
      console.log("Missing code parameter", code);
      return new Response("Missing code parameter", { status: 400 });
    }

    let userData: UserData;
    try {
      const decodedCode = atob(code);
      userData = JSON.parse(decodedCode) as UserData;

      if (!userData.firstName || !userData.lastName || !userData.email) {
        console.log("Invalid code: missing required fields", userData);
        return new Response("Invalid code: missing required fields", {
          status: 400,
        });
      }
    } catch {
      console.log("Invalid code: not a valid BASE64 encoded JSON", code);
      return new Response("Invalid code: not a valid BASE64 encoded JSON", {
        status: 400,
      });
    }

    try {
      const tokens = await generateTokens(userData, env);

      return new Response(JSON.stringify(tokens), {
        status: 200,
        headers: {
          "Content-Type": "application/json",
        },
      });
    } catch (error) {
      console.error("Error creating tokens:", error);
      return new Response("Internal Server Error", { status: 500 });
    }
  } else if (grantType === "refresh_token") {
    if (!refreshToken) {
      console.log("Missing refresh_token parameter");
      return new Response("Missing refresh_token parameter", { status: 400 });
    }

    try {
      const jwks = jose.createRemoteJWKSet(
        new URL(`${env.AUTH_ISSUER}/.well-known/jwks.json`)
      );

      // Verify the refresh token using the public key
      const { payload } = await jose.jwtVerify(refreshToken, jwks, {
        issuer: env.AUTH_ISSUER,
        audience: "local-anode-client",
      });

      // Extract user data from the refresh token
      const userData: UserData = {
        firstName: payload.given_name as string,
        lastName: payload.family_name as string,
        email: payload.email as string,
      };

      // Generate new tokens
      const tokens = await generateTokens(userData, env);

      return new Response(JSON.stringify(tokens), {
        status: 200,
        headers: {
          "Content-Type": "application/json",
        },
      });
    } catch (error) {
      console.error("Error verifying refresh token:", error);
      return new Response("Invalid refresh token", { status: 400 });
    }
  } else {
    console.log("Invalid grant_type", grantType);
    return new Response("Invalid grant_type", { status: 400 });
  }
}

async function handleUserinfo(request: Request, env: Env): Promise<Response> {
  const authHeader = request.headers.get("Authorization");
  if (!authHeader || !authHeader.startsWith("Bearer ")) {
    return new Response("Missing or invalid Authorization header", {
      status: 401,
      headers: {
        "WWW-Authenticate": "Bearer",
      },
    });
  }

  const accessToken = authHeader.substring(7);

  try {
      const jwks = jose.createRemoteJWKSet(
        new URL(`${env.AUTH_ISSUER}/.well-known/jwks.json`)
      );

      const { payload } = await jose.jwtVerify(accessToken, jwks, {
        issuer: env.AUTH_ISSUER,
        audience: "local-anode-client",
      });

    const userinfo = {
      sub: payload.sub,
      given_name: payload.given_name,
      family_name: payload.family_name,
      email: payload.email,
    };

    return new Response(JSON.stringify(userinfo), {
      status: 200,
      headers: {
        "Content-Type": "application/json",
        "Access-Control-Allow-Origin": "*",
        "Access-Control-Allow-Methods": "GET, OPTIONS",
        "Access-Control-Allow-Headers": "Content-Type, Authorization",
      },
    });
  } catch (error) {
    console.error("Error verifying access token:", error);
    return new Response("Invalid access token", {
      status: 401,
      headers: {
        "WWW-Authenticate": "Bearer",
      },
    });
  }
}

interface JWK {
  kty: string;
  use: string;
  kid: string;
  n: string;
  e: string;
}

interface JWKS {
  keys: JWK[];
}

async function handleJwks(_request: Request, env: Env): Promise<Response> {
  try {
    const pem = await ensurePEM(env);
    const privateKey = await jose.importPKCS8(pem, "RS256", {
      extractable: true,
    });

    const publicKey = await jose.exportJWK(privateKey);

    const jwk: JWK = {
      kty: publicKey.kty!,
      use: "sig",
      kid: "1",
      n: publicKey.n!,
      e: publicKey.e!,
    };

    const jwks: JWKS = {
      keys: [jwk],
    };

    return new Response(JSON.stringify(jwks, null, 2), {
      status: 200,
      headers: {
        "Content-Type": "application/json",
        "Access-Control-Allow-Origin": "*",
        "Access-Control-Allow-Methods": "GET, OPTIONS",
        "Access-Control-Allow-Headers": "Content-Type",
      },
    });
  } catch (error) {
    console.error("Error generating JWKS:", error);
    return new Response("Internal Server Error", { status: 500 });
  }
}

export async function handleOidcRequest(
  request: Request,
  env: Env
): Promise<Response> {
  const url = new URL(request.url);
  const pathname = url.pathname;

  if (request.method === "OPTIONS") {
    return new Response(null, {
      status: 200,
      headers: {
        "Access-Control-Allow-Origin": "*",
        "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
        "Access-Control-Allow-Headers": "Content-Type, Authorization",
      },
    });
  }

  if (pathname === "/local_oidc/.well-known/openid-configuration") {
    return handleOpenIdConfiguration(request, env);
  }

  if (pathname === "/local_oidc/.well-known/jwks.json") {
    return handleJwks(request, env);
  }

  if (pathname === "/local_oidc/token") {
    return handleToken(request, env);
  }

  if (pathname === "/local_oidc/userinfo") {
    return handleUserinfo(request, env);
  }

  return new Response("Not Found", { status: 404 });
}
