export function getEssentialPackages(): string[] {
  return [
    "ipython",
    "matplotlib",
    "numpy",
    "pandas",
    "polars",
    "duckdb",
    "pyarrow",
    "requests",
    "micropip",
    "pyodide-http",
    "scipy",
    "sympy",
    "bokeh",
    "scikit-learn",
    "altair",
    "geopandas",
    "rich",
    "networkx",
    "beautifulsoup4",
    "lxml",
    "pillow",
    "statsmodels",
  ];
}
