#!/usr/bin/env node

import { readFileSync, writeFileSync, existsSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const projectRoot = join(__dirname, "..");

// Check if running as postinstall hook
const isPostInstall = process.env.npm_lifecycle_event === "postinstall";

// Check if running in production/preview environment
const deploymentEnv = process.env.DEPLOYMENT_ENV;
const isProductionLike =
  deploymentEnv === "production" || deploymentEnv === "preview";

function createEnvFiles() {
  // Skip creating development files in production/preview environments
  if (isProductionLike) {
    if (!isPostInstall) {
      console.log(
        `⚠️  Skipping .env file creation in ${deploymentEnv} environment`,
      );
    }
    return;
  }
  const kernelEnvPath = join(
    projectRoot,
    "packages",
    "pyodide-runtime-agent",
    ".env",
  );
  const docworkerDevVarsPath = join(
    projectRoot,
    "packages",
    "docworker",
    ".dev.vars",
  );

  let created = [];

  // Create kernel server .env (server-only vars, including API keys)
  if (!existsSync(kernelEnvPath)) {
    const kernelEnvContent = `# Anode Kernel Server Environment
# Auto-generated by setup script
# NOTE: These variables are server-only and not exposed to the browser

# LiveStore Sync Backend URL (for kernel server connection)
LIVESTORE_SYNC_URL=ws://localhost:8787

# OpenAI API Key for AI cells (uncomment and add your key)
# Get your key from: https://platform.openai.com/api-keys
# OPENAI_API_KEY=your-openai-api-key-here

# Authentication token for sync backend (fallback when Google OAuth not used)
AUTH_TOKEN=insecure-token-change-me
`;
    writeFileSync(kernelEnvPath, kernelEnvContent);
    created.push("kernel server");
  }

  // Create docworker .dev.vars (wrangler dev secrets)
  if (!existsSync(docworkerDevVarsPath)) {
    const docworkerDevVarsContent = `# Anode Docworker Development Secrets
# Auto-generated by setup script
# NOTE: This file is used by wrangler dev for local development secrets

# Authentication token for sync backend (matches other packages)
AUTH_TOKEN=insecure-token-change-me
`;
    writeFileSync(docworkerDevVarsPath, docworkerDevVarsContent);
    created.push("docworker");
  }

  if (created.length > 0) {
    console.log(`✅ Created .env file(s) for: ${created.join(", ")}`);
  } else if (!isPostInstall) {
    console.log("✅ Development environment files already exist");
  }
}

function validateEnvironment() {
  // Skip validation in production/preview environments
  if (isProductionLike) {
    if (!isPostInstall) {
      console.log(
        `✅ Skipping environment validation in ${deploymentEnv} environment`,
      );
    }
    return true;
  }

  const kernelEnvPath = join(
    projectRoot,
    "packages",
    "pyodide-runtime-agent",
    ".env",
  );
  const docworkerDevVarsPath = join(
    projectRoot,
    "packages",
    "docworker",
    ".dev.vars",
  );

  // Check kernel server .env
  if (!existsSync(kernelEnvPath)) {
    console.error("❌ kernel server .env file not found");
    return false;
  }

  // Check docworker .dev.vars
  if (!existsSync(docworkerDevVarsPath)) {
    console.error("❌ docworker .dev.vars file not found");
    return false;
  }

  const kernelEnvContent = readFileSync(kernelEnvPath, "utf8");
  const docworkerDevVarsContent = readFileSync(docworkerDevVarsPath, "utf8");

  // Validate kernel server .env has LIVESTORE_SYNC_URL
  if (!kernelEnvContent.includes("LIVESTORE_SYNC_URL=")) {
    console.error("❌ Missing LIVESTORE_SYNC_URL in kernel server .env");
    return false;
  }

  // Validate docworker .dev.vars has AUTH_TOKEN
  if (!docworkerDevVarsContent.includes("AUTH_TOKEN=")) {
    console.error("❌ Missing AUTH_TOKEN in docworker .dev.vars");
    return false;
  }

  if (!isPostInstall) {
    console.log("✅ Environment configuration is valid");
    console.log(
      "💡 Web client uses .env.development/.env.production (pre-configured)",
    );
  }
  return true;
}

function checkPorts() {
  console.log("\n🔍 Port Configuration:");
  console.log("  - Web Client: http://localhost:5173");
  console.log("  - Sync Backend: ws://localhost:8787");
  console.log("  - Make sure these ports are available");
}

function showNextSteps() {
  console.log("\n🚀 Next Steps:");
  console.log("  1. Start development: pnpm dev");
  console.log("  2. Open http://localhost:5173");
  console.log("  3. Create a notebook and get kernel command from UI");
  console.log(
    "  4. Start runtime: NOTEBOOK_ID=your-notebook-id pnpm dev:runtime",
  );
  console.log("\n💡 Optional Setup:");
  console.log(
    "    - Add OpenAI API key to packages/pyodide-runtime-agent/.env",
  );
  console.log(
    "    - Web client OAuth settings are in .env.development/.env.production",
  );
  console.log(
    "    - Set GOOGLE_CLIENT_ID secret in Cloudflare Worker for production",
  );
  console.log("    (All secrets are kept server-side for security)");
}

function main() {
  if (!isPostInstall) {
    if (isProductionLike) {
      console.log(
        `🚀 Running in ${deploymentEnv} environment - skipping development setup\n`,
      );
    } else {
      console.log("🔧 Setting up Anode development environment...\n");
    }
  }

  createEnvFiles();

  if (validateEnvironment()) {
    if (!isPostInstall && !isProductionLike) {
      checkPorts();
      showNextSteps();
      console.log("\n✅ Setup complete! Ready to develop.");
    } else if (!isPostInstall && isProductionLike) {
      console.log(`\n✅ ${deploymentEnv} environment setup complete.`);
    }
  } else {
    console.log("\n❌ Setup failed. Please check the errors above.");
    process.exit(1);
  }
}

main();
