name: Auto Deploy Preview

on:
  push:
    branches: [main]

jobs:
  auto-deploy-preview:
    name: Auto Deploy Preview
    uses: ./.github/workflows/.deploy-reusable.yml
    with:
      environment: "preview"
      build_mode: "preview"
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
