name: Deploy Preview Manually

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Branch, tag, or commit SHA to deploy"
        required: false
        default: "main"
        type: string

jobs:
  deploy-preview:
    name: Deploy Preview Manually
    uses: ./.github/workflows/_deploy-reusable.yml
    with:
      environment: "preview"
      build_mode: "preview"
      branch: ${{ github.event.inputs.ref }}
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
